### ISSUE TITLE
Inversion of colors at Google Search

### ISSUE THREAD

**Issue by planet17** [liorgrossman/darkness#65]
I think inversion it is not well idea!

Looks why: http://joxi.ru/xAevl1EiYKpVOr

At whole site I got inverted colors. But I trying look content what must display without inversion.

**Comment by planet17** [comment]
The same case at all themes.
I using preview look.

**Comment by theme1256** [comment]
I would disagree and agree with your statement that inversion is a bad idea.
It's a great place to start, but not a complete solution, that's why we have this plugin, where it's possible to fix the mistakes that may occur when inverting everything.
If you look through the source code you will see that it's not just inversion, far from it.

I fixed the color picker on Google (http://puu.sh/yvhLb/8ebe4603c2.jpg) and I don't understand what the problem is, what content is inverted that shouldn't be? videos, images, gifs? Please send us a screenshot.

**Comment by liorgrossman** [comment]
I agree with @theme1256 here.

Inversion has it's problems, sure. However, the alternative is manually trying to style all DOM elements in a page to have a dark color. What usually happens is that:
1. You never get 100% coverage (all the pages and all dialogs seen by all users of a website)
2. The site often gets new UI elements which are then bright.
So instead of occasional bugs like the one you described (the lesser of two evils), you get screaming white in the middle of a dark page, which is worse IMHO.

@theme1256 - thanks for the fix. I'm closing this ticket for now.
@planet17 - if you encounter any other inversions issues, please open another ticket, or push a fix to the codebase (pull requests are more than welcome!)

**Comment by planet17** [comment]
@theme1256  Yeah, I had mean only color picker. On my screen it had been selected blue color, but how you can see display orange.
I didnt know, why I had seen not fixed color. Just maybe I looks into "preview version".

**Comment by planet17** [comment]
@theme1256 
About inversion in any way, I just had said my opinion.
I think my knowledge of CSS - worse. So I just suggested it.
Thanks for tell me why I can be wrong!
